package com.exam.examserver.enums;

public enum NotificationAction {
    FILE_PENDING_REVIEW, FILE_APPROVED, FILE_REJECTED, FILE_DELETED,
    TASK_ASSIGNED, TASK_UPDATED, TASK_CANCELLED, TASK_STARTED, TASK_SUBMITTED, TASK_RETURNED, TASK_APPROVED, TASK_REPORTED,
    QUESTION_FLAGGED, QUESTION_UNFLAGGED
}
